"""add assignee to appointment

Revision ID: 355d777ad154
Revises: 6bca7ca82e54
Create Date: 2026-04-30 12:02:56.255598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355d777ad154'
down_revision = '6bca7ca82e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sa.String(length=10), nullable=False, server_default='marie'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
