"""Add group_id, service_code, and block_index to Appointment

Revision ID: 6bca7ca82e54
Revises: 
Create Date: 2025-11-23 13:50:36.399975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bca7ca82e54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('service_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('block_index', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('block_index')
        batch_op.drop_column('service_code')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
